zuul:
  prefix: /api
  routes:
    user-service:
      path: /users/**
      serviceId: user-service
    post-service:
      path: /posts/**
      serviceId: post-service
    notification-service:
      path: /notifications/**
      serviceId: notification-service
    happening-service:
      path: /happenings/**
      serviceId: happening-service